### PR TITLE
Allow text-2.0

### PR DESCRIPTION
**Pull request by ysangkok**
Tested using

    cabal test --constraint='text>=2'

### CODE REVIEW

**Comment by ysangkok** [comment]
Thanks for the merge! Since this is only a metadata change, it can be applied to an existing release using the "edit package information" button on [the hackage page for the package](https://hackage.haskell.org/package/wl-pprint-annotated). Would you be willing to do that?

**Comment by ysangkok** [comment]
ping @minad , see previous message

**Comment by minad** [comment]
Hey @ysangkok, I am currently not actively maintaining this package. So it may take some time until I get to it.

**Comment by ysangkok** [comment]
@minad If you like, you can add me to the maintainers, then I will make the revision, and keep the package compatible with newer GHCs (in the future, when necessary). Here is my user: https://hackage.haskell.org/user/janus

**Comment by minad** [comment]
Okay, I've added you.

**Comment by ysangkok** [comment]
Thank you! I have revised version 0.1.0.1 on Hackage. Cheers!

**Pull request merged**
